import { SheetsTableColumn } from "@/components/SheetsTable";

/**
 * Standard column definitions for EMoU records
 * Matching exact order and widths from the Home page table
 */

export const standardColumns: SheetsTableColumn[] = [
  {
    key: "id",
    label: "ID",
    width: "100px",
    editable: false,
  },
  {
    key: "companyName",
    label: "Company Name",
    width: "200px",
    editable: true,
    type: "text",
  },
  {
    key: "department",
    label: "Department",
    width: "100px",
    editable: true,
    type: "select",
    selectOptions: [
      "CSE",
      "ECE",
      "MECH",
      "CIVIL",
      "EEE",
      "IT",
      "AIDS",
      "CSBS",
      "E&I",
      "MECHATRONICS",
      "CCE",
      "AIML",
      "CYBERSECURITY",
      "IOT",
      "EICE",
      "CSE MTECH",
      "Institution",
      "Incubation",
    ],
  },
  {
    key: "scope",
    label: "Scope",
    width: "120px",
    editable: true,
    type: "select",
    selectOptions: ["National", "International"],
  },
  {
    key: "maintainedBy",
    label: "Maintained By",
    width: "140px",
    editable: true,
    type: "select",
    selectOptions: ["Departments", "Institution", "Incubation"],
  },
  {
    key: "fromDate",
    label: "From Date",
    width: "100px",
    editable: true,
    type: "date",
  },
  {
    key: "toDate",
    label: "To Date",
    width: "100px",
    editable: true,
    type: "date",
  },
  {
    key: "status",
    label: "Status",
    width: "110px",
    editable: false,
  },
  {
    key: "documentAvailability",
    label: "Doc Availability",
    width: "150px",
    editable: true,
    type: "select",
    selectOptions: ["Available", "Not Available"],
  },
  {
    key: "hodApprovalDoc",
    label: "HO Approval",
    width: "180px",
    editable: false,
  },
  {
    key: "signedAgreementDoc",
    label: "Signed Agreement",
    width: "180px",
    editable: false,
  },
  {
    key: "description",
    label: "Description",
    width: "250px",
    editable: true,
    type: "textarea",
    truncate: 80,
  },
  {
    key: "aboutCompany",
    label: "About Company",
    width: "200px",
    editable: true,
    type: "textarea",
    truncate: 50,
  },
  {
    key: "companyAddress",
    label: "Company Address",
    width: "200px",
    editable: true,
    type: "textarea",
    truncate: 50,
  },
  {
    key: "companyWebsite",
    label: "Company Website",
    width: "180px",
    editable: true,
    type: "text",
  },
  {
    key: "companyRelationship",
    label: "Relationship",
    width: "90px",
    editable: true,
    type: "select",
    selectOptions: ["1", "2", "3", "4", "5"],
  },
  {
    key: "industryContactName",
    label: "Industry Contact",
    width: "150px",
    editable: true,
    type: "text",
  },
  {
    key: "industryContactMobile",
    label: "Industry Mobile",
    width: "120px",
    editable: true,
    type: "text",
  },
  {
    key: "industryContactEmail",
    label: "Industry Email",
    width: "180px",
    editable: true,
    type: "text",
  },
  {
    key: "institutionContactName",
    label: "Institution Contact",
    width: "150px",
    editable: true,
    type: "text",
  },
  {
    key: "institutionContactMobile",
    label: "Institution Mobile",
    width: "120px",
    editable: true,
    type: "text",
  },
  {
    key: "institutionContactEmail",
    label: "Institution Email",
    width: "180px",
    editable: true,
    type: "text",
  },
  {
    key: "clubsAligned",
    label: "Clubs Aligned",
    width: "150px",
    editable: true,
    type: "text",
  },
  {
    key: "sdgGoals",
    label: "SDG Goals",
    width: "150px",
    editable: true,
    type: "text",
  },
  {
    key: "skillsTechnologies",
    label: "Skills/Technologies",
    width: "200px",
    editable: true,
    type: "textarea",
    truncate: 50,
  },
  {
    key: "perStudentCost",
    label: "Per Student Cost",
    width: "90px",
    editable: true,
    type: "number",
  },
  {
    key: "placementOpportunity",
    label: "Placement",
    width: "90px",
    editable: true,
    type: "number",
  },
  {
    key: "internshipOpportunity",
    label: "Internship",
    width: "90px",
    editable: true,
    type: "number",
  },
  {
    key: "goingForRenewal",
    label: "Renewal",
    width: "80px",
    editable: true,
    type: "select",
    selectOptions: ["Yes", "No"],
  },
  {
    key: "benefitsAchieved",
    label: "Benefits Achieved",
    width: "200px",
    editable: true,
    type: "textarea",
    truncate: 50,
  },
  {
    key: "createdByName",
    label: "Created By",
    width: "120px",
    editable: false,
  },
];

/**
 * Admin approval columns - same as standard for consistency
 */
export const approvalColumns: SheetsTableColumn[] = standardColumns;

/**
 * Compact columns for overview
 */
export const compactColumns: SheetsTableColumn[] = [
  {
    key: "id",
    label: "ID",
    width: "100px",
    editable: false,
  },
  {
    key: "companyName",
    label: "Company Name",
    width: "200px",
    editable: true,
    type: "text",
  },
  {
    key: "department",
    label: "Department",
    width: "100px",
    editable: true,
    type: "select",
    selectOptions: [
      "CSE",
      "ECE",
      "MECH",
      "CIVIL",
      "EEE",
      "IT",
      "AIDS",
      "CSBS",
      "E&I",
      "MECHATRONICS",
      "CCE",
      "AIML",
      "CYBERSECURITY",
      "IOT",
      "EICE",
      "CSE MTECH",
      "Institution",
      "Incubation",
    ],
  },
  {
    key: "fromDate",
    label: "From Date",
    width: "100px",
    editable: true,
    type: "date",
  },
  {
    key: "toDate",
    label: "To Date",
    width: "100px",
    editable: true,
    type: "date",
  },
  {
    key: "status",
    label: "Status",
    width: "110px",
    editable: false,
  },
  {
    key: "description",
    label: "Description",
    width: "250px",
    editable: true,
    type: "textarea",
    truncate: 80,
  },
  {
    key: "hodApprovalDoc",
    label: "HO Approval",
    width: "150px",
    editable: false,
  },
  {
    key: "signedAgreementDoc",
    label: "Signed Agreement",
    width: "150px",
    editable: false,
  },
  {
    key: "createdByName",
    label: "Created By",
    width: "120px",
    editable: false,
  },
];
